language: php

sudo: true

cache: composer

php:
  - 7.1
  - 7.2

stages:
  - test
  - name: documentation
    if: branch = master

jobs:
  include:
    - stage: test
      script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
      script: php vendor/bin/php-coveralls -v
    - stage: documentation
      script: sudo apt-get install graphviz
      script: php vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: build/docs
        on:
          branch: master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist
  - travis_retry phpenv rehash