language: php

sudo: true

php:
 - 7.2
 - 7.1


cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - test
  - name: documentation
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: documentation
      install: true
      before_install:
        - sudo apt-get update
        - sudo apt-get install graphviz
      script:
        - php vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"
      after_success: skip
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: build/docs
        on:
          branch: master

    - stage: deploy
      before_script: skip
      script:
        - nvm install 10 && nvm use 10
        - npm install
        - npm run semantic-release

before_script:
  - travis_retry composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/php-coveralls -v

