language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - precache
  - test
  - name: documentation
    if: branch = master

jobs:
  include:
    - stage: precache
      script: true
      php: 7.2

    - stage: test
      script:
        - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
      php:
        - 7.1
        - 7.2
      after_success:
        - php vendor/bin/php-coveralls -v

    - stage: documentation
      install: true
      before_install:
        - sudo apt-get update
        - sudo apt-get install graphviz
      script:
        - php vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: build/docs
        on:
          branch: master

before_script:
  - travis_retry composer install --prefer-dist
  - travis_retry phpenv rehash