language: php

sudo: false

cache: composer

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install -n --prefer-dist
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then php vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"; fi

after_script:
  - php vendor/bin/php-coveralls -v

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build/docs
  on:
    branch: master